notifications:
  email: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils
language: node_js
sudo: false
node_js:
  - stable
script:
  - commitlint-travis
install:
  - npm install
test:
  - npm run test
after_success:
  - npm run semantic-release
